//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNAwesomeService.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DNNAwesome_Customer
    {
        public DNNAwesome_Customer()
        {
            this.DNNAwesome_Order = new HashSet<DNNAwesome_Order>();
        }
    
        public int CustomerID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string ZipCode { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual DNNAwesome_Status DNNAwesome_Status { get; set; }
        public virtual ICollection<DNNAwesome_Order> DNNAwesome_Order { get; set; }
    }
}
