//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNNAwesomeService.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DNNAwesomeEntities : DbContext
    {
        public DNNAwesomeEntities()
            : base("name=DNNAwesomeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DNNAwesome_Customer> DNNAwesome_Customer { get; set; }
        public virtual DbSet<DNNAwesome_Order> DNNAwesome_Order { get; set; }
        public virtual DbSet<DNNAwesome_Status> DNNAwesome_Status { get; set; }
    }
}
